### ISSUE TITLE
Use ladybird as the standard browser

### ISSUE THREAD

**Issue by ghost** [Arcanyx-org/NiXium#82]
Ladybird is an independent, brand-new web browser built entirely from scratch. The original founder and creator, [Andreas Kling](https://github.com/awesomekling), is an expert in operating systems and web browser development, with experience at both Nokia and Apple. He also played a significant role in developing WebKit. Currently, Ladybird is backed and funded by a non-profit organization and a few sponsors, making its ecosystem and potential very promising.

Note: At the moment, Ladybird is in a pre-alpha state and only suitable for use by developers

## References

- [Ladybird GitHub Repository](https://github.com/LadybirdBrowser/ladybird)
- [Ladybird Homepage](https://ladybird.org)
- [Ladybird Announcement](https://ladybird.org/announcement.html)

**Comment by Kreyren** [comment]
Another alternative https://github.com/schizofox/schizofox

**Comment by Kreyren** [comment]
I tried ladybird 0-unstable-2024-06-08 provided in nixos's stable and unstable channel and the web browser is very unusable atm it has isssues:
* Loading websites correctly
* Performance
* console outputs a bunch of errors and fixmes
* likely has a bunch of security issues and is very fingerprintable due to it being a very young project

So for now i don't see that as a good idea to use it as a standard web browser, we can revisit that once it's codebase is stabilized (re-open the issue then)
